[package]
name = "frcw"
version = "0.1.0"
authors = ["Parker J. Rule <parker.rule@tufts.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.64", features = ["derive"] }
serde_json = "1.0.64"
clap = "2.33.3"
rand = { version = "0.8.3", features = ["small_rng"] }
mimalloc = { version = "0.1.25", default-features = false }
crossbeam-channel = "0.5.0"
crossbeam = "0.8.0"
sha3 = "0.9.1"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
debug = false
lto = true
codegen-units = 1
panic = "abort"
