[package]
name = "recom-rust"
version = "0.1.0"
authors = ["Parker J. Rule <parker.rule@tufts.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.64"
clap = "2.33.3"
rand = { version = "0.8.3", features = ["small_rng"] }

[profile.dev]
opt-level = 3
debug = false

[profile.release]
debug = true
